image: gradle:jdk21-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false -Dorg.gradle.caching=true"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches
     - .gradle/build-cache

stages:
  - build
  - deploy

build:
  stage: build
  script: ./gradlew --build-cache assemble
  only:
    - tags
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

deploy:
  stage: deploy
  script: ./gradlew publish
  only:
    - tags
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

